FROM apache/airflow:3.1.0

USER root

# Instala dependências do sistema para o Driver SQL Server
RUN apt-get update && apt-get install -y gnupg2 curl ca-certificates gcc g++ unixodbc-dev

# Adiciona o repositório da Microsoft para Debian 12 (Bookworm)
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg && \
    echo "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" > /etc/apt/sources.list.d/mssql-release.list

# Instala o Driver ODBC 18 (mais atual)
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18

USER airflow

# Instala os provedores específicos para a versão 3
# Note que usamos o 'odbc' para evitar conflitos com o 'pymssql'
RUN pip install --upgrade pip && \
    pip install \
    apache-airflow-providers-odbc \
    apache-airflow-providers-amazon \
    apache-airflow-providers-sftp \
    pyodbc pandas sqlalchemy